repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: (thirdparty/.*)|(SOPHUS_VERSION)|(.txt)$
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list
          - "te,tring,crate"
