[package]
description = "sophus - geometry for robotics and computer vision"
name = "sophus_image"
readme = "../../README.md"

edition.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
sophus_core.workspace = true

approx.workspace = true
assertables.workspace = true
bytemuck.workspace = true
nalgebra.workspace = true
ndarray.workspace = true
num-traits.workspace = true
png.workspace = true
tiff.workspace = true

[features]
simd = ["sophus_core/simd"]
