name: clippy
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  clippy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Run sccache stat for check before
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: cargo clippy
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: |
          rustup default nightly
          rustup component add clippy
          cargo clippy --all-targets --all-features
      - name: Run sccache stat for check after
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
