name: docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
      runs-on: ubuntu-22.04
      env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
      steps:
        - name: Checkout workspace
          uses: actions/checkout@v4
        - name: Run sccache-cache
          uses: mozilla-actions/sccache-action@v0.0.9
        - uses: extractions/setup-just@v1
        - name: cargo doc
          run: |
            rustup default nightly
            rustup component add rustfmt
            just doc
