name: main
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nasm
          cargo doc --no-deps
          cargo fmt --check
          cargo test --release
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release
          working-directory: crates/sophus_pyo3
     


