name: main
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo
        run: |
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
          cargo fmt
          cargo check
          cargo clippy
          cargo test
     



