name: nightly
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-24.04

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: extractions/setup-just@v1
      - name: cargo build
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: |
          rustup default nightly
          just build-simd
      - name: cargo test
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: |
          rustup default nightly
          just test-simd
