name: nightly
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-24.04

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: extractions/setup-just@v1
      - name: Install nightly
        run: |
          rustup toolchain install nightly
          rustup default nightly
      - name: cargo build
        run: just build-simd
      - name: cargo test
        run: just test-simd
