name: stable
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  stable:
    runs-on: ubuntu-22.04

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: extractions/setup-just@v1
      - name: cargo build
        run: just build-std
      - name: cargo test
        run: just test
      - name: cargo clippy
        run: |
          rustup component add clippy
          just clippy
